version: '3.8'

services:
  # External notifier service
  notifier:
    image: igodwin/notifier:latest
    container_name: secretsanta-notifier
    ports:
      - "50051:50051"  # gRPC port
      - "8080:8080"    # HTTP REST API port
    environment:
      - LOG_LEVEL=info
      - GRPC_PORT=50051
      - HTTP_PORT=8080
    volumes:
      - ./configs/notifier.yaml:/app/config.yaml:ro
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - secretsanta-network

  # Secret Santa web server
  secretsanta-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: secretsanta-web
    ports:
      - "8081:8080"  # Web UI and API
    volumes:
      - ./configs/config.yaml:/app/config.yaml:ro
    depends_on:
      notifier:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - secretsanta-network

  # Development environment with both services
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    container_name: secretsanta-dev
    environment:
      - NOTIFIER_SERVICE_ADDR=notifier:50051
    volumes:
      - .:/app
      - /app/bin  # Exclude bin directory
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]  # Keep container running
    depends_on:
      notifier:
        condition: service_healthy
    networks:
      - secretsanta-network
    profiles:
      - dev

networks:
  secretsanta-network:
    driver: bridge

volumes:
  notifier-data:
    driver: local