# Secret Santa Configuration File

smtp:
  host: "smtp.example.com"
  port: "587"
  identity: ""
  username: "your-email@example.com"
  password: "YOUR_SMTP_PASSWORD"
  from_address: "your-email@example.com"
  from_name: "Your Name"

notifier:
  # Optional: Use external notifier service via gRPC
  # service_addr: "localhost:50051"

  # Optional: Archive email for BCC - useful for keeping records of all assignments
  # archive_email: "secretsanta-archive@example.com"
