# Configuration for the external notifier service
server:
  grpc:
    port: 50051
    host: "0.0.0.0"
  http:
    port: 8080
    host: "0.0.0.0"

logging:
  level: "info"
  format: "json"

# Notification providers configuration
providers:
  smtp:
    host: "smtp.example.com"
    port: 587
    username: "your-email@example.com"
    password: "YOUR_SMTP_PASSWORD"
    from: "Secret Santa <secretsanta@example.com>"
    
  slack:
    webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
    
  ntfy:
    server_url: "https://ntfy.sh"
    topic: "secretsanta-notifications"

# Queue configuration
queue:
  type: "memory"  # or "redis" for production
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0

# Retry configuration
retry:
  max_attempts: 3
  initial_delay: "1s"
  max_delay: "30s"
  backoff_multiplier: 2.0